// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLz8HJkfbLl_jv7Ayjz8S4z3IflSLLZIU',
    appId: '1:678549860039:web:2146d2c243a42c82b318e2',
    messagingSenderId: '678549860039',
    projectId: 'runtahpedia-88ed0',
    authDomain: 'runtahpedia-88ed0.firebaseapp.com',
    storageBucket: 'runtahpedia-88ed0.firebasestorage.app',
    measurementId: 'G-Y63JB2LYRS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdreW7SXPPL3h4w6CnyhvRUq8Pnd3H3eI',
    appId: '1:678549860039:ios:ad0ff4524ca75b50b318e2',
    messagingSenderId: '678549860039',
    projectId: 'runtahpedia-88ed0',
    storageBucket: 'runtahpedia-88ed0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdreW7SXPPL3h4w6CnyhvRUq8Pnd3H3eI',
    appId: '1:678549860039:ios:ad0ff4524ca75b50b318e2',
    messagingSenderId: '678549860039',
    projectId: 'runtahpedia-88ed0',
    storageBucket: 'runtahpedia-88ed0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
