// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJ-fwusWzZjIU2ZR9nay0TjS1Xn9UHt8',
    appId: '1:1054199043550:web:db56aadd4deb68da3db94f',
    messagingSenderId: '1054199043550',
    projectId: 'runtahpedia2',
    authDomain: 'runtahpedia2.firebaseapp.com',
    storageBucket: 'runtahpedia2.firebasestorage.app',
    measurementId: 'G-0WD8XKJPJ7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoIEbApgyySDM3uZWZuOO-Pqib0CYJp8',
    appId: '1:1054199043550:ios:fad1c1308fc5201e3db94f',
    messagingSenderId: '1054199043550',
    projectId: 'runtahpedia2',
    storageBucket: 'runtahpedia2.firebasestorage.app',
    iosBundleId: 'com.richart.runtahpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoIEbApgyySDM3uZWZuOO-Pqib0CYJp8',
    appId: '1:1054199043550:ios:02fbe215bc87c9ee3db94f',
    messagingSenderId: '1054199043550',
    projectId: 'runtahpedia2',
    storageBucket: 'runtahpedia2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}